//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsYourProblemCSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUser
    {
        public PUser()
        {
            this.ChatComments = new HashSet<ChatComment>();
            this.Problems = new HashSet<Problem>();
        }
    
        public System.Guid ID { get; set; }
        public string Email { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.Guid> EmailCode { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public Nullable<int> FailedPasswordCount { get; set; }
        public Nullable<bool> Online { get; set; }
    
        public virtual ICollection<ChatComment> ChatComments { get; set; }
        public virtual ICollection<Problem> Problems { get; set; }
    }
}
